## Otel Configuration for AppDynamics Java Agent
## Traces only for now

extensions:
  health_check:
    check_collector_pipeline:
      enabled: true
      interval: "15s"
      exporter_failure_threshold: 5
  pprof:
    endpoint: localhost:1777
  zpages:
    endpoint: localhost:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource:
    attributes:
      - key: appdynamics.controller.account
        action: upsert
        value: "se-lab"
      - key: appdynamics.controller.host
        action: upsert
        value: "se-lab.saas.appdynamics.com"
      - key: appdynamics.controller.port
        action: upsert
        value: 443
  batch:
    timeout: 5s
    send_batch_size: 5

exporters:
  debug :
    verbosity : detailed
  file/combined :
    path : ./otel-agent/logs/combined-all.log
  otlphttp:
    endpoint: "https://pdx-sls-agent-api.saas.appdynamics.com"
    headers: {"x-api-key": "b21aef0d4d5241660633bf833337b6a4ad40e27e5668b9c7f96a0ea4b704bbd2"}

service:
  extensions : [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp, file/combined]

