apiVersion: v1
kind: Namespace
metadata:
  name: rest-appdynamics
---
apiVersion: v1
kind: Service
metadata:
  name: rest-appdynamics-service
  namespace: rest-appdynamics
spec:
  selector:
    app: rest-appdynamics
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-appdynamics
  namespace: rest-appdynamics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-appdynamics
  template:
    metadata:
      labels:
        app: rest-appdynamics
    spec:
      containers:
        - name: rest-appdynamics
#          image: hughbrien/rest-appdynamics:release-1.0.0
          image: hbrien622/rest-appdynamics_amd64:1.0.1
          imagePullPolicy : Always
          ports:
            - containerPort: 8083
          securityContext :
            allowPrivilegeEscalation : false
          livenessProbe :
            httpGet :
              path : /actuator
              port : 8083
            initialDelaySeconds : 30
            timeoutSeconds : 15
          readinessProbe :
            httpGet :
              path : /actuator
              port : 8083
            initialDelaySeconds : 30
            periodSeconds : 60



