apiVersion: v1
kind: Namespace
metadata:
  name: restapplication
---
apiVersion: v1
kind: Service
metadata:
  name: rest-application-service
  namespace: restapplication
spec:
  selector:
    app: rest-application
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-application
  namespace: restapplication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-application
  template:
    metadata:
      labels:
        app: rest-application
    spec:
      containers:
        - name: rest-application
          image: hbrien622/rest-application:1.0.1
          imagePullPolicy : Always
          ports:
            - containerPort: 8083
          securityContext :
            allowPrivilegeEscalation : false
          livenessProbe :
            httpGet :
              path : /actuator/health/liveness
              port : 8083
            initialDelaySeconds : 30
            timeoutSeconds : 15
          readinessProbe :
            httpGet :
              path : /actuator/health/readiness
              port : 8083
            initialDelaySeconds : 30
            periodSeconds : 60



