apiVersion: v1
kind: Namespace
metadata:
  name: restapplication
---
apiVersion: v1
kind: Service
metadata:
  name: restapplication-service
  namespace: restapplication
spec:
  selector:
    app: restapplication
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapplication
  namespace: restapplication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restapplication
  template:
    metadata:
      labels:
        app: restapplication
    spec:
      containers:
        - name: restapplication
#          image: hughbrien/restapplication:release-1.0.0
          image: hbrien622/restapplication_amd64:1.0.2
          imagePullPolicy : Always
          ports:
            - containerPort: 8083
          securityContext :
            allowPrivilegeEscalation : false
          livenessProbe :
            httpGet :
              path : /actuator
              port : 8083
            initialDelaySeconds : 30
            timeoutSeconds : 15
          readinessProbe :
            httpGet :
              path : /actuator
              port : 8083
            initialDelaySeconds : 30
            periodSeconds : 60



