global:
  clusterName: macos-cluster
appdynamics-smartagent:
  solution:
    endpoint: https://lab1.observe.appdynamics.com
  oauth:
    clientId: agt_keQPaYdJTpkrGqZ6zlqmT
    clientSecret: sKsVpEO6L6aLxfjg30O1cF4CNJswVYAa0luQclDszfc
    tokenUrl: https://lab1.observe.appdynamics.com/auth/dfdbdf71-7322-44d0-85fb-36c69a7c3789/default/oauth2/token
    tenantId: dfdbdf71-7322-44d0-85fb-36c69a7c3789
---
global:
  clusterName: macos-cluster
appdynamics-cloud-k8s-monitoring:
  install:
    clustermon: true
    defaultInfraCollectors: true
    logCollector: true
  clustermonConfig:
    os: linux
  containermonConfig:
    os:
      - linux
  servermonConfig:
    os:
      - linux
  logCollectorConfig:
    os:
      - linux
    container:
      defaultConfig:
        enabled: true
appdynamics-otel-collector:
  clientId: agt_keQPaYdJTpkrGqZ6zlqmT
  clientSecret: sKsVpEO6L6aLxfjg30O1cF4CNJswVYAa0luQclDszfc
  endpoint: https://lab1.observe.appdynamics.com/data
  tokenUrl: https://lab1.observe.appdynamics.com/auth/dfdbdf71-7322-44d0-85fb-36c69a7c3789/default/oauth2/token
