            - name: DynatraceAction
  # You may pin to the exact commit or the version.
  # uses: dynatrace-oss/dynatrace-github-action@9193965d5d57be3a3718df3595bb515d50f4f664
  uses: dynatrace-oss/dynatrace-github-action@v9
  with:
    # A valid Dynatrace URL
    url: 
    # A valid Dynatrace API-token
    token: 
    # A list of metrics objects to send
    metrics: # optional, default is []
    # A list of event objects to send
    events: # optional, default is []
          
