name: Post JSON or YAML to Endpoint

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  post-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send JSON or YAML to endpoint
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
      run: |
        # Choose your payload format
        PAYLOAD='{
          "event": "deployment",
          "status": "success",
          "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
        }'

        # Alternatively, use YAML payload
        # PAYLOAD=$(cat <<EOF
        # event: deployment
        # status: success
        # timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
        # EOF
        # )

        curl -X POST "$ENDPOINT_URL" \
          -H "Authorization: Bearer $API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD"
