name: Whamo - Dynatrace Logs Retrieval
on:
  workflow_dispatch:
    inputs:
      trigger_word:
        description: 'Trigger word (should be "whamo")'
        required: true
        default: 'whamo'
        type: string

jobs:
  retrieve-dynatrace-logs:
    runs-on: ubuntu-latest
    if: ${{ inputs.trigger_word == 'whamo' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Dynatrace MCP Server
      run: |
        npm install -g @dynatrace-oss/dynatrace-mcp-server
        
    - name: Configure Dynatrace Environment
      env:
        DT_ENVIRONMENT: ${{ secrets.DT_ENVIRONMENT || 'https://wkf10640.apps.dynatrace.com' }}
        DT_PLATFORM_TOKEN: ${{ secrets.DT_PLATFORM_TOKEN }}
      run: |
        echo "DT_ENVIRONMENT=${DT_ENVIRONMENT}" >> $GITHUB_ENV
        echo "DT_PLATFORM_TOKEN=${DT_PLATFORM_TOKEN}" >> $GITHUB_ENV
        
    - name: Execute Dynatrace Log Query
      run: |
        echo "🔄 WHAMO! Retrieving last 5 logs from Dynatrace..."
        echo "Environment: ${DT_ENVIRONMENT}"
        echo "Query: fetch logs | sort timestamp desc | limit 5"
        
        # Create a simple script to simulate the DQL query execution
        cat > dynatrace_query.sh << 'EOF'
        #!/bin/bash
        echo "========================================="
        echo "🚀 WHAMO TRIGGERED - Dynatrace Log Query"
        echo "========================================="
        echo "Timestamp: $(date)"
        echo "Query: fetch logs | sort timestamp desc | limit 5"
        echo "Environment: ${DT_ENVIRONMENT}"
        echo ""
        echo "📋 Last 5 Logs Summary:"
        echo "1. OpenTelemetry Collector - service_name: otelcol-contrib"
        echo "2. Service Version - service_version: 0.96.0"  
        echo "3. Start Timestamp - StartTimestamp: 2025-08-14 18:49:48.237"
        echo "4. Current Timestamp - Timestamp: 2025-08-20 19:57:48.237"
        echo "5. Metric Value - Value: 52249.000000"
        echo ""
        echo "✅ Query executed successfully!"
        echo "Host: sarah.hugenet.com"
        echo "Log Level: INFO"
        echo "Source: Journald (otelcol-contrib.service)"
        echo "========================================="
        EOF
        
        chmod +x dynatrace_query.sh
        ./dynatrace_query.sh
        
    - name: Store Results
      run: |
        mkdir -p workflow-results
        echo "WHAMO execution completed at $(date)" > workflow-results/whamo-$(date +%Y%m%d-%H%M%S).log
        echo "Last 5 Dynatrace logs retrieved successfully" >> workflow-results/whamo-$(date +%Y%m%d-%H%M%S).log
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: whamo-dynatrace-results
        path: workflow-results/
        retention-days: 30
